Repository function-junctions/function-junctions, pull requests merged in 2023-09, with the labels that each got.

#35 feat: building internal state management tool
  packages/config/eslint-config-custom/index.js
  packages/config/tsconfig/library.json
  packages/react/vite.config.ts
  packages/shared/package.json
  packages/shared/src/__tests__/test.test.ts
  packages/shared/src/components/Proxyable/index.ts
  packages/shared/src/components/Proxyable/utils/proxyable.test.ts
  packages/shared/src/components/Proxyable/utils/proxyable.ts
  packages/shared/src/components/index.ts
  packages/shared/vite.config.ts
  packages/svelte/vite.config.ts
  packages/vanilla/vite.config.ts
  yarn.lock
Labels: core

#41 feat: create tree builder with inputs and outputs
  packages/config/eslint-config-custom/index.js
  packages/shared/src/components/IO/index.ts
  packages/shared/src/components/IO/utils/Input.ts
  packages/shared/src/components/IO/utils/Output.test.ts
  packages/shared/src/components/IO/utils/Output.ts
  packages/shared/src/components/IO/utils/index.ts
  packages/shared/src/components/InputBuilder/index.ts
  packages/shared/src/components/InputBuilder/modules/InputBuilder.ts
  packages/shared/src/components/InputBuilder/modules/index.ts
  packages/shared/src/components/NodesInputsTreeBuilder/index.ts
  packages/shared/src/components/NodesInputsTreeBuilder/modules/NodesInputsTreeBuilder.test.ts
  packages/shared/src/components/NodesInputsTreeBuilder/modules/NodesInputsTreeBuilder.ts
  packages/shared/src/components/NodesInputsTreeBuilder/modules/index.ts
  packages/shared/src/components/NodesInputsTreeBuilder/utils/deserializeInputTree.ts
  packages/shared/src/components/NodesInputsTreeBuilder/utils/index.ts
  packages/shared/src/components/NodesOutputsTreeBuilder/index.ts
  packages/shared/src/components/NodesOutputsTreeBuilder/modules/NodesOutputsTreeBuilder.ts
  packages/shared/src/components/NodesOutputsTreeBuilder/modules/index.ts
  packages/shared/src/components/NodesOutputsTreeBuilder/utils/deserializeOutputTree.ts
  packages/shared/src/components/NodesOutputsTreeBuilder/utils/index.ts
  packages/shared/src/components/Observable/index.ts
  packages/shared/src/components/Observable/modules/Observable.ts
  packages/shared/src/components/Observable/modules/UnifiedObservable.test.ts
  packages/shared/src/components/Observable/modules/UnifiedObservable.ts
  packages/shared/src/components/Observable/modules/index.ts
  packages/shared/src/components/Output/index.ts
  packages/shared/src/components/Output/modules/Output.ts
  packages/shared/src/components/Output/modules/index.ts
  packages/shared/src/components/Proxyable/index.ts
  packages/shared/src/components/Proxyable/utils/index.ts
  packages/shared/src/components/Proxyable/utils/proxyable.test.ts
  packages/shared/src/components/Proxyable/utils/proxyable.ts
  packages/shared/src/components/TreeBuilder/index.ts
  packages/shared/src/components/TreeBuilder/modules/TreeBuilder.ts
  packages/shared/src/components/TreeBuilder/modules/index.ts
  packages/shared/src/components/index.ts
Labels: enhancement, Impact 🚀

#42 chore: create barrell exports rule
  packages/config/eslint-config-custom/index.js
  packages/shared/src/components/NodesInputsTreeBuilder/utils/deserializeInputTree.ts
  packages/shared/src/components/NodesOutputsTreeBuilder/modules/NodesOutputsTreeBuilder.ts
Labels: enhancement, Impact 🚗
